version: '3.8'

services:
  react-app:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production

  flask-api:
    build:
      context: ./api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/api
    environment:
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - FLASK_ENV=development
      - FLASK_APP=app.py
    command: flask run --host=0.0.0.0
